[package]
name = "http"
version = "0.0.1"
authors = ["Andrew Doble"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Use heapless for fixed-size strings and collections
heapless = "0.8.0"
httparse = {version = "1.10.1", default-features = false}
nourl = "0.1.4"


