[package]
name = "http-builder"
version = "0.1.0"
authors = ["Andrew Doble"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Use heapless for fixed-size strings and collections
heapless = "0.8.0"

