[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"


[env]
ESP_LOG="info"

# Tuning base on https://github.com/esp-rs/esp-hal/issues/1605#issuecomment-2133150064
# WARNING: Any changes in these environment varaibles has to be followed by 
# a clean build for them to take effect. 
ESP_WIFI_CONFIG_RX_QUEUE_SIZE       =	"20"
ESP_WIFI_CONFIG_TX_QUEUE_SIZE       =	"5"
ESP_WIFI_CONFIG_STATIC_RX_BUF_NUM	=   "10"
ESP_WIFI_CONFIG_DYNAMIC_RX_BUF_NUM	=   "16"
ESP_WIFI_CONFIG_STATIC_TX_BUF_NUM	=   "0"
ESP_WIFI_CONFIG_DYNAMIC_TX_BUF_NUM	=   "16"
ESP_WIFI_CONFIG_AMPDU_RX_ENABLE     =	"true"
ESP_WIFI_CONFIG_AMPDU_TX_ENABLE     =	"true"
ESP_WIFI_CONFIG_RX_BA_WIN           =	"6"
ESP_WIFI_CONFIG_MAX_BURST_SIZE      =	"8"

#ESP_WIFI_CONFIG_MTU = "6000"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  # ALSO see this for a what options are required: https://docs.esp-rs.org/esp-hal/esp-wifi/0.10.1/esp32c3/esp_wifi/
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tlinkall.x",
  #"-C", "link-arg=-Trom_functions.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]
